### ISSUE TITLE
Implement Copy and Paste Functionality for wasm target

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#1]
Wasm can be done using https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html with async API, ideally may be upstreamed to `arboard`.

**Comment by bytemunch** [comment]
I've been trying to implement without using crossbeam (cos lazy and I didn't wanna learn another API lol) but it looks like that's the easiest way forward. Thought my async bevy understanding wasn't too bad, but wasm does single threaded async which throws everything off a bit.

Copy and Cut were easy enough, reading back the clipboard contents for Paste is the only sticking point. `JsValue` isn't `Send` and all my `Task<T>` stuff is replaced with `FakeTask` in wasm land.

Should have it working once crossbeam is in.

**Comment by Dimchikkk** [comment]
never heard about crossbeam :D

**Comment by bytemunch** [comment]
It's a channel crate, actually very easy to use. I should be more open to using extra crates. Got clipboard contents `console.log`-ing in browser now, nearly there

**Comment by Dimchikkk** [comment]
I see, I've used https://crates.io/crates/async-channel in `velo`.

**Comment by Dimchikkk** [comment]
> It's a channel crate, actually very easy to use. I should be more open to using extra crates. Got clipboard contents `console.log`-ing in browser now, nearly there

Make sure to test on Chrome :D

**Comment by bytemunch** [comment]
Yeah I'm a chrome user :) I hadn't even thought about browser compatibility, I think any browser that follows the clipboard API spec will work. Chrome did ask permission for the clipboard tho which is a bit of a pain, not sure there's anything we can do to skip that
