### ISSUE TITLE
Allow plugin's user to change font_color

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#10]
It's hardcoded currently: https://github.com/StaffEngineer/bevy_cosmic_edit/blob/3123ef0032a9f4c8518e8ad920d369d4edfcd767/src/lib.rs#L1029

**Comment by bytemunch** [comment]
oops my bad, this should pull from `attrs` somehow. was using font_per_widget to check color was working so didn't catch this, giving it a shot now
