### ISSUE TITLE
Pressing HOME or END on an empty widget with placeholder panics

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#102]
cosmic-text throws `layout not found`, linked to [this](https://github.com/pop-os/cosmic-text/blob/163d8ef26e0eb1049f13e211071f7da5775cba1f/src/buffer.rs#L497) upstream TODO

May be trying to move underlying cursor to out of bounds position

DOWN and UP arrows also panic

PGDOWN and PGUP also panic, but only after the widget has had text and then it has been deleted.

**Comment by Dimchikkk** [comment]
I remember experiencing similar issues... and it was hotfixed by https://github.com/StaffEngineer/bevy_cosmic_edit/blob/63c17ca38021197f3bd9c326c2f1a8fb44d43dde/src/lib.rs#L126

**Comment by bytemunch** [comment]
Seems like the Placeholder is hitting that line, must be an issue with the actual buffer missing layout info then. I guess it's not shaped or anything when empty?

In the rabbit hole I've found that the `BufferLine` has a `layout()` function, calling it could prevent the 'layout not found' stuff.

Think I need a nap the password input had me running in circles all day haha, I'll take a fresh look another time.
