### ISSUE TITLE
Pressing `Enter` on wasm sends `E` and `Delete` sends `D` in `text_input` example

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#107]
Needs investigation, unsure if I re-introduced the bug, browser change, winit change, bevy change, or environmental on my end

**Comment by bytemunch** [comment]
Upon further testing this issue seems to only be present in the `test_input` example, possibly something to do with removing/switching editors on the same frame as pressing return.

**Comment by bytemunch** [comment]
Delete key adds a D on text_input, but not on other examples. Strange one, perhaps it's due to reading the character events twice in a frame?

**Comment by bytemunch** [comment]
Ah I've found it, it's because of `prevent_default_event_handling: false`. @StaffEngineer what was the purpose of setting this option?

**Comment by Dimchikkk** [comment]
don't remember :D
