### ISSUE TITLE
`InfiniteLine` cursor position is broken in latest update

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#109]

**Comment by bytemunch** [comment]
With recent changes `InfiniteLine` inputs do not follow the cursor.

@StaffEngineer Should `InfiniteLine` mode be a plugin?

**Comment by Dimchikkk** [comment]
> @StaffEngineer Should InfiniteLine mode be a plugin?

Ideally yes but I am not sure how feasible this is.
