### ISSUE TITLE
Bevy 0.12 support

### ISSUE THREAD

**Issue by iggedi-ig-ig** [StaffEngineer/bevy_cosmic_edit#117]
As the title suggests, `bevy_cosmic_edit` doesn't have support for bevy 0.12 yet.

**Comment by Dimchikkk** [comment]
Yep, that's a good first issue :) I expect close to zero changes... make sure to update Readme :)

EDIT: apparently there are some changes

**Comment by bytemunch** [comment]
Yeah I've been fiddling with it for a bit, AssetsV2 causes some issues with the default image switching stuff

**Comment by bytemunch** [comment]
Got it! Testing now, pr incoming :)
