### ISSUE TITLE
0.15 is not on crates.io yet

### ISSUE THREAD

**Issue by iggedi-ig-ig** [StaffEngineer/bevy_cosmic_edit#121]
Maybe there is a reason for this, but in case this was forgotten I thought I might just open an issue for this :)

**Comment by Dimchikkk** [comment]
Published bevy_cosmic_edit v0.15.1 at registry `crates-io`

There is a bug for Retina display users with scaling, I'll publish new version once it's fixed upstream in 0.12.1
