### ISSUE TITLE
Update to latest on crates.io

### ISSUE THREAD

**Issue by ChaoticWagon** [StaffEngineer/bevy_cosmic_edit#150]
The latest version on crates.io is not compatible with bevy 0.14.0

**Comment by Dimchikkk** [comment]
Yeah, I haven't released it since the latest version that compatible with 0.14 has some new bugs on wasm32, e.g. https://github.com/Dimchikkk/bevy_cosmic_edit/issues/149

I don't have capacity for fixing those bugs by myself at the moment, so I published the latest version to crates.io anyway.
