### ISSUE TITLE
Cannot type spaces into cosmic text bundle

### ISSUE THREAD

**Issue by IrrelevantGaymer** [StaffEngineer/bevy_cosmic_edit#151]
input.rs line 499 in function kb_input_text only checks for Key::Character(char) and not Key::Space, meaning that CosmicTextBundle's do not register space key events.

**Comment by Dimchikkk** [comment]
is it the same issue: https://github.com/Dimchikkk/bevy_cosmic_edit/issues/149 ?

**Comment by IrrelevantGaymer** [comment]
It probably is, because looking at the code, space doesn't work no matter what.  I can close this ticket and add this information to #149, if you'd like.  Also at some point, I'll create a new fork pushing some fixes.

**Comment by databasedav** [comment]
i broke this here https://github.com/Dimchikkk/bevy_cosmic_edit/pull/148/files#diff-b28dbadb7b0fb54a6a72860d79ba4fa2c1228788e81a14dbd99f8536f5e317a9R499 during the bevy 0.14 upgrade, didn't realize entire classes of keystrokes would be excluded

how can this be solved in a general way? does just adding handling for `Key::Space` suffice?

**Comment by Dimchikkk** [comment]
I am on vacation, can't look now, pinging @bytemunch if he has an idea :)

**Comment by IrrelevantGaymer** [comment]
Just took a look through Bevy's Key enum, Space should be sufficient, however you might want to add something for Tabs cause I don't think they are handled either.  Other than that, I don't think there's any other typeable character that's not included in the Key::Character variant.
