### ISSUE TITLE
how to use external fonts?

### ISSUE THREAD

**Issue by databasedav** [StaffEngineer/bevy_cosmic_edit#157]
for example, if i want to use the `FiraMono-Medium.ttf` font packaged with bevy, i have the following code
```rust
let font_bytes: &[u8] = include_bytes!("../assets/fonts/FiraMono-Medium.ttf");
let font_config = CosmicFontConfig {
    fonts_dir_path: None,
    font_bytes: Some(vec![font_bytes]),
    load_system_fonts: true,
};

App::new()
    .add_plugins(DefaultPlugins)
    .add_plugins(CosmicEditPlugin {
        font_config,
        ..default()
    })
```
but specifying `attrs = attrs.family(Family::Name("Fira Mono"));` doesn't seem to do anything, how do i tell which `Family::Name` string actually maps to the fira mono .ttf? `attrs = attrs.family(Family::Name("Victor Mono"));` works as expected

**Comment by Dimchikkk** [comment]
Victor Mono Regular has normal font weight that is 400 (this is default weight), Fira Mono Medium has medium font weight that is 500. To use Fira Mono Medium have to set font weight to medium:

```rust
    attrs = attrs.family(Family::Name("Fira Mono"));
    attrs = attrs.weight(FontWeight::MEDIUM);
```
