### ISSUE TITLE
Closing the app window for any of the examples causes a panic 

### ISSUE THREAD

**Issue by iancormac84** [StaffEngineer/bevy_cosmic_edit#160]
The panic occurs at [line 213](https://github.com/Dimchikkk/bevy_cosmic_edit/blob/main/src/buffer.rs#L213) with the code ` let w_scale = window_q.single().scale_factor();`

Is the fix for this to just check whether calling the `single()` method returns a window and simply returning if not, before calling `scale_factor()`?

**Comment by Dimchikkk** [comment]
> Is the fix for this to just check whether calling the `single()` method returns a window and simply returning if not, before calling `scale_factor()`?

Yep
