### ISSUE TITLE
Allow users to use bevy_cosmic_edit plugin without cosmic-text dependency

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#2]
One approach is to re-export `cosmic-text` types.

**Comment by bytemunch** [comment]
Another way would be wrapping all the times we use cosmic-text structs in intermediary structs and then converting types in a function. This approach increases complexity, and from what I've seen is not the idiomatic way to go.

I think re-exporting the user facing types is the way forward, the only drawback I can find in discussion online is that the plugin would be semver-coupled to cosmic-text, when they bump we'd have to check if public API for the types we re-export have changed and bump accordingly. Seems a minor inconvenience for the ease of install needing less extra deps would bring.

Currently across the examples, we import or use:

 - `Color` : We have `bevy_color_to_cosmic` for this. (though may need to check alpha support)
 - `Attrs` and `AttrsOwned` : Lots of wrangling between the two in practice, API could be simpler, and in simplifying may abstract the types away
 - `Family` : This feels fine to re-export as-is, perhaps as `FontFamily` for clarity?
 - `Style` and `Weight` : Also feel fine to re-export, `FontStyle` + `FontWeight` maybe?

So 6 exports at most, assuming the examples cover all code paths that may need a cosmic-text type.

@StaffEngineer Have you come across any more cosmic-text imports in velo?

**Comment by Dimchikkk** [comment]
Based on `velo` usages it is all you mentioned + `use cosmic_text::{Cursor, Edit, Action};`

**Comment by Dimchikkk** [comment]
NIce investigation, I didn't expect that it's so few of them :)

**Comment by bytemunch** [comment]
There may be more, I'm gonna make an example that uses every option to create an editor, will see what else needs re-exported and what can be cut out and left as default every time

**Comment by bytemunch** [comment]
Setting the `editor` directly requires `cosmic_text::{Editor, Buffer, Metrics}`. I can't think of a use case that would need to set the editor directly on instantiation though. Which makes having the option kind of redundant, could detect addition of a tag component and add the editor to the entity in a function similar to `cosmic_editor_builder` https://github.com/StaffEngineer/bevy_cosmic_edit/blob/7380648a995c8c3dae5748ceba876771445981ec/src/lib.rs#L136

The function basically overwrites the editor that is added by default every time, which feels wasteful and should probably be changed anyway.

So my plan is to remove the unnecessary `editor` field from the `CosmicEdit` bundles, and rewrite the `cosmic_editor_builder` function to accommodate this change.

@StaffEngineer can you think of a use case that needs to define the editor in a specific way, or is creating an empty buffer, calling `set_text`, and injecting metrics from the `CosmicMetrics` field enough?

**Comment by Dimchikkk** [comment]
@bytemunch 

not really. will plugin users be able to access cosmic editor instance?

`velo` calls `get_y_offset` func directly for "clickable links" feature that requires buffer.

**Comment by bytemunch** [comment]
I think so, my rust-fu isn't quite at the level I can answer that without implementing and testing, but I'll make sure to try it :)

**Comment by Dimchikkk** [comment]
@bytemunch yeah, make sure that arguments for all public functions can still be accessed, then all should be fine :)

**Comment by bytemunch** [comment]
Ah yes, calling `editor.buffer()` needs the `cosmic_text::Edit` trait in scope. This could be mitigated by passing the `CosmicEditor` wrapper component instead and then getting the buffer in `lib.rs` where `cosmic_text` is already in scope:

```rs
fn example(editor_q: Query<&CosmicEditor>) {
  let editor = editor_q.single();
  bevy_cosmic_edit::get_x_offset(editor);
}
```

And there would need to be a new function for every other buffer operation, which is getting way too into the weeds of wrapping and converting every call. Still, avenue explored.

Taking a cursory look at `velo`'s code, I think having direct access to the buffer will be required for anything other than simple text operations, so I'd say the `Edit` trait definitely needs to be re-exported.

So the list is `Edit`, `Cursor`, `Action`, `Attrs`, `AttrsOwned`, `Family`, `Style`, and `Weight`. `Color` is gonna be binned in favour of `bevy_color_to_cosmic` on all operations, until I learn how to implement a `From<T>` thing lol.

**Comment by Dimchikkk** [comment]
Sounds good.

**Comment by Dimchikkk** [comment]
@bytemunch `From<T>` should be quite easy to implement: https://github.com/StaffEngineer/velo/blob/b75fa7c770ed5bb78652dcb508382c64152d7e4b/src/utils.rs#L89-L105 😉
