### ISSUE TITLE
Provide max character / max line limits

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#22]
Will make #17 simpler as single line inputs will be a common use-case, and adds ways for such limits to extend to other use cases (e.g. username length limits)

**Comment by Dimchikkk** [comment]
Nice idea, I just hacked single line inputs by disabling editing on enter in `velo`: https://github.com/StaffEngineer/velo/blob/b75fa7c770ed5bb78652dcb508382c64152d7e4b/src/ui_plugin/systems/keyboard.rs#L150

this is a proper fix 👍
