### ISSUE TITLE
Use smaller bundled fallback font

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#25]
Currently VictorMono is bundled, and has a fair footprint. Ideally the font should be as small as reasonably possible, as it will be included in all builds and downloads.

**Comment by Dimchikkk** [comment]
Bevy uses 20KB font as default: https://github.com/bevyengine/bevy/pull/8445/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R229

**Comment by bytemunch** [comment]
ah that's the one you meant, i was looking in the assets folder. will pop it in now

**Comment by bytemunch** [comment]
FiraMono-subset doesn't seem to play nice, thought I'd be able to just swap the files out in a quick patch job but needs further investigation, back to being a tomorrow job D:

**Comment by Dimchikkk** [comment]
No hurry at all... ideally if we could add to the plugin fetching font from any url on wasm...there is another plugin that already fetching assets from web, we just need to repeat the same code and supply font to plugin.
