### ISSUE TITLE
Refactor API to look like native bevy API

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#3]

**Comment by bytemunch** [comment]
Just cloned the repo to have a read of the code, I might give this a shot. If I understand correctly we should be able to spawn a CosmicEdit just like a TextBundle?

**Comment by Dimchikkk** [comment]
Currently to create `cosmic_edit` text input a font system should be created:
```rs
    let cosmic_font_config = CosmicFontConfig {
        fonts_dir_path: None,
        font_bytes: Some(vec![font_bytes]),
        load_system_fonts: true,
    };
    let font_system = create_cosmic_font_system(cosmic_font_config);
    let font_system_handle: Handle<CosmicFont> = cosmic_fonts.add(CosmicFont(font_system));
   ```
   
   and then using `font_system_handle` multiple `cosmic_edit` text inputs can be created like so:
   
   ```rs
    let cosmic_edit_meta = CosmicEditMeta {
        text: CosmicText::OneStyle("😀😀😀 x => y".to_string()),
        attrs: AttrsOwned::new(attrs),
        text_pos: CosmicTextPos::Center,
        bg: Color::WHITE,
        metrics: CosmicMetrics {
            font_size: 14.,
            line_height: 18.,
            scale_factor,
        },
        font_system_handle,
        node: CosmicNode::Sprite(CosmicEditSprite {
            transform: Transform {
                translation: Vec3::new(0., 0., 1.),
                ..default()
            },
        }),
        size: Some((primary_window.width(), primary_window.height())),
        readonly: false,
        bg_image: None,
    };
    let cosmic_edit = spawn_cosmic_edit(&mut commands, &mut cosmic_fonts, cosmic_edit_meta);
   ```
   
  The idea is to improve above api to look more like native bevy api.... for example `bevy_prototype_lyon` api looks something like this:
  ```rs
    let points = [
        Vec2::new(-width / 2., -height / 2.),
        Vec2::new(-width / 2., height / 2.),
        Vec2::new(width / 2., height / 2.),
        Vec2::new(width / 2., -height / 2.),
    ];
    let path: Path = bevy_prototype_lyon::shapes::RoundedPolygon {
       points: points.into_iter().collect(),
       closed: true,
       radius: 10.,
    };
    let shape = commands
        .spawn((
            bevy_prototype_lyon::prelude::ShapeBundle {
                transform: Transform {
                    translation: Vec3::new(0.0, 0.0, 0.001),
                    ..default()
                },
                path,
                ..default()
            },
            Stroke::new(
                if has_border {
                    theme.node_border
                } else {
                    Color::NONE
                },
                1.,
            ),
            Fill::color(item_meta.pair_bg_color.1)
        ))
        .id();
```
  
   Notice `ShapeBundle` api (and the whole workflow of `shape` creation) feels similar to `TextBundle` api (looks like native bevy api), so the goal is to change `cosmic_edit` api to look like native too.

**Comment by bytemunch** [comment]
So I've got this working to spawn a cosmic text box:
```rust
commands.spawn(CosmicEditUiBundle {
    style: Style {
        width: Val::Px(300.),
        height: Val::Px(50.),
        left: Val::Px(100.),
        top: Val::Px(100.),
        ..default()
    },
    ..default()
});
```

...but I've borked the image clearing somehow. Investigating now.

I should also learn how to make a PR again at some point lol

---

typical, just fixed the clearing minutes after posting an update
its working woo

**Comment by Dimchikkk** [comment]
> I should also learn how to make a PR again at some point lol

Quite similar to https://github.com/StaffEngineer/velo/blob/main/contributing.md

**Comment by bytemunch** [comment]
oh cool seems simple enough. I've made a whole lot of breaking changes so I'll need to refactor tests and examples too, will send a PR when that's done

**Comment by Dimchikkk** [comment]
Nice, no hurry, if you want to refactor https://github.com/StaffEngineer/velo codebase (it heavily uses bevy_cosmic_edit) for the new API feel free, if not - I can adjust it by myself once your changes are merged :)

**Comment by Dimchikkk** [comment]
@bytemunch do you need any help? :)

**Comment by bytemunch** [comment]
All good, not been stuck with anything just simple lack of time, just moved and not got broadband transferred yet 😭 Should be able to get the refac finished tomorrow, if all goes well in life 🙏

**Comment by Dimchikkk** [comment]
@bytemunch all the best anyway 🙏 ❤️

**Comment by bytemunch** [comment]
Alright now I might need a hand, I seem to have broken MultiStyle text and I'm not sure where, could you have a check please? 

https://github.com/bytemunch/bevy_cosmic_edit/tree/bevy_like_api

**Comment by Dimchikkk** [comment]
Hi @bytemunch , I am on vacation with phone without laptop, so I can only take look in a week of so.

**Comment by bytemunch** [comment]
ah no worries, enjoy your time off :) i found the culprit, I had some misplaced logic
