### ISSUE TITLE
Re-export cosmic_text::Color

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#33]
would replace `bevy_color_to_cosmic` and make code prettier :)

**Comment by bytemunch** [comment]
I seem to be fighting against Rust with this one, trying to define `impl From`s on two foreign types.

https://stackoverflow.com/questions/71000682/is-possible-to-implement-traits-on-foreign-types

I tried making an intermediary type and defining `From<bevy::Color>` and `From<cosmic_text::Color>` on it, but `.into()` doesn't look like it'll follow a chain to get to the correct type. I guess it couldn't, it'd have to somehow check every possible chain of `From`s which is exponentially time consuming.

The other option is a wrapper struct, something like `BevyColorWrapper(Color::RED).into()` would net a `cosmic_text::Color`, but at that point `bevy_color_to_cosmic(Color::RED)` is simpler anyway.

I'm dropping this for now. Defeated by `From` again looool

**Comment by Dimchikkk** [comment]
ah yeah, foreign types traits :/

**Comment by Dimchikkk** [comment]
@bytemunch you could try something like this:

```rs
pub struct MyColor(pub bevy::prelude::Color);

impl From<Color> for MyColor {
    fn from(color: Color) -> Self {
        Self(color)
    }
}

impl From<MyColor> for cosmic_text::Color {
    fn from(color: MyColor) -> Self {
        cosmic_text::Color::rgba(
            (color.0.r() * 255.) as u8,
            (color.0.g() * 255.) as u8,
            (color.0.b() * 255.) as u8,
            (color.0.a() * 255.) as u8,
        )
    }
}

fn test(c: MyColor) {}
fn test2(c: cosmic_text::Color) {}

fn test_main() {
    test(Color::WHITE.into());
    test2(Into::<MyColor>::into(Color::WHITE).into());
    let color: MyColor = Color::WHITE.into();
    test2(color.into());
}
```

The code above compiles but I am not sure it's better than having one converter func.

**Comment by bytemunch** [comment]
Yea, converter function is the simplest it seems. Could consider re-exporting `cosmic_text::Color` as `CosmicColor` or something

**Comment by Dimchikkk** [comment]
Yeah, re-exporting cosmic color sounds promising :)

**Comment by StaffEngineer** [comment]
I've re-exported `Color as CosmicColor`. bevy colors have convenient GREEN, YELLOW, etc declarations, so let's keep the function for converting from bevy color to cosmic too. Let's user decide what to use: bevy colors + converter func or re-exported CosmicColor directly.

**Comment by Dimchikkk** [comment]
I've exported CosmicColor and mover bevy_color_to_cosmic to userland.
