### ISSUE TITLE
Rename `set_text` to `text` :)

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#34]
https://github.com/StaffEngineer/bevy_cosmic_edit/blob/5157cb3f575b192dafcb3aabb9eb6e2f20ea8c5a/src/lib.rs#L286

~~(set_text is a bit weirdly looking, would be cool to implement syncing and rename it to text)~~

**Comment by bytemunch** [comment]
ideally we'd have change detection on the `Buffer` but will have to implement that in a system, then update the `CosmicText` when the buffer has different contents from the previous frame. I don't have the code open at the moment, but I feel creating a `CosmicText::MultiStyle` from buffer contents may be the main challenge here, grabbing the correct `attrs` for each span and stuff

**Comment by Dimchikkk** [comment]
maybe we just then return back `set_text` function? :) and to get anything user have to call `get_text` func... to get raw string and user will have access to other stuff to get styling of text

```rs
set_text: CosmicText => void
get_text: () => String
```

EDIT: Or maybe we just rename `set_text` to `text` and all is fine fow now lol
