### ISSUE TITLE
Consistent helper function location

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#39]
With `bevy_color_to_cosmic` in userland, should the click handlers follow? Conversely should the color converter be in `utils.rs`?

**Comment by Dimchikkk** [comment]
I guess, yep. In `velo` I have custom interactive sprite system (https://github.com/StaffEngineer/velo/blob/main/src/ui_plugin/systems/interactive_sprites.rs#L19)... or users may use `bevy_mod_picking` for sprite interactions so they won't use `change_active_editor_sprite` and `change_active_editor_ui` is trivial.
