### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#41]
https://github.com/StaffEngineer/bevy_cosmic_edit/actions/runs/6220242769/job/16879866636?pr=40

```
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_249.11-0ubuntu3.9_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
```

**Comment by Dimchikkk** [comment]
Let's fix it with some PR as soon as someone feel fixing it lol

**Comment by bytemunch** [comment]
Yeah I'm afraid I'm clueless when it comes to CI :(

**Comment by Dimchikkk** [comment]
@bytemunch ci is fixed here: https://github.com/StaffEngineer/bevy_cosmic_edit/pull/44
