### ISSUE TITLE
Add selection word/paragraph on mouse click

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#45]
1-mouse-click: place cursor (already implemented by cosmic-text)
2-clicks: select word
3-clicks: select paragraph
(mimic behaviour of google translate text selection on mouse clicking)

**Comment by bytemunch** [comment]
I just went to try implement this and added a couple args to the `cosmic_edit_bevy_events` function.. Totalling 30, breaking bevy's limit :S Gonna try breaking the input function apart first

**Comment by Dimchikkk** [comment]
> Your function can have a maximum of 16 total parameters. If you need more, group them into tuples to work around the limit. Tuples can contain up to 16 members, but can be nested indefinitely.

(https://bevy-cheatbook.github.io/programming/systems.html#systems)

**Comment by Dimchikkk** [comment]
Sky is the limit :)
