### ISSUE TITLE
Dark theme colors support

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#49]
```rs
    let attrs = AttrsOwned::new(Attrs::new().color(CosmicColor::rgb(255, 255, 255)));
    ...
    background_color: Color::BLACK.into(),
```
Expected: white font on black background
Actual:
<img width="510" alt="image" src="https://github.com/StaffEngineer/bevy_cosmic_edit/assets/111751109/94cf4662-5e9a-470d-9405-9f9176981006">

**Comment by bytemunch** [comment]
Hm, this one's being tricky. Not sure where but it feels like the bgcolor and text color are being mixed at some point? Using a `bevy::Color::rgb(0.1,0.1,0.1)` background and white text gives a very washed out result.

**Comment by Dimchikkk** [comment]
Yep, I suppose it's mixing here: https://github.com/StaffEngineer/bevy_cosmic_edit/blob/main/src/lib.rs#L1459. I suppose we have to mix it to get anti-aliasing. How to get white-font then 🤔 One thing I'd start is to look into cosmic-text example repos... maybe we have to adopt another draw_pixel function I dunno.

**Comment by bytemunch** [comment]
Yeah I've been learning all about alpha blending and the different methods that there are. I'm not too savvy with the bitwise operations but they're almost definitely needed for perf reasons. Example repos is a good shout, I'll go do some reading

**Comment by bytemunch** [comment]
I am losing my mind, I have an alpha blend function that works in a standalone crate with dummy data, as soon as I put it in a cosmic text context it gives garbled colors. Tried switching between rgba and argb. Overwriting a black buffer color with anything but 0 alpha doesn't have any effect.

Imma look at this again later, I may be missing something in the `editor.draw()` call, or something in `swash` that is messing me up.

Or I have a typo lol

**Comment by bytemunch** [comment]
Back from my two week nap :)

![alpha_lol](https://github.com/StaffEngineer/bevy_cosmic_edit/assets/43527203/4f1a55c2-f914-49f5-a34c-221a900aedc8)

Just noticed there's a difference between UI and Sprite color blending oh nooooooo now I'm more confused

**Comment by Dimchikkk** [comment]
hmmm

**Comment by Dimchikkk** [comment]
maybe just save the image cosmic-text generates and see how it looks originally?

**Comment by bytemunch** [comment]
Well I've fixed White text on Black background hahaha 
![fixed](https://github.com/StaffEngineer/bevy_cosmic_edit/assets/43527203/af55db30-8533-48cb-9100-061e847abb2d)

I'm sure I've got my math wrong somewhere, or something is under/overflowing. Every time I adjust the math to fix one of the widgets, the others break. This is using straight blending at the moment, I'll try implementing premultiplied and see if there's any change.

Pulling the raw pixels out is a good idea, I think maybe UI and Sprite rendering use `rgba` in different orders, dumping the buffer should prove or disprove that

**Comment by bytemunch** [comment]
Okay, some real progress. Still gotta look into the UI/Sprite differences, but thanks to [NVIDIA's post](https://developer.nvidia.com/content/alpha-blending-pre-or-not-pre) I've got a handle on blending.

![sprites_working](https://github.com/StaffEngineer/bevy_cosmic_edit/assets/43527203/53567f55-3765-43f1-87dd-a1301232a075)

**Comment by Dimchikkk** [comment]
Looks cool. Maybe you need to unset background of UI node.

**Comment by bytemunch** [comment]
Yeah you got me looking in the right place, UI nodes were being tinted by their background colors. Just tidying up before PR now :D
