### ISSUE TITLE
Support placeholder text

### ISSUE THREAD

**Issue by Dimchikkk** [StaffEngineer/bevy_cosmic_edit#54]
If input is empty show placeholder that has configurable styling different from main text
<img width="281" alt="image" src="https://github.com/StaffEngineer/bevy_cosmic_edit/assets/111751109/dc229c09-93bd-454b-b0db-4a14c58dcf04">

**Comment by Dimchikkk** [comment]
@bytemunch wanna tackle this? :)

**Comment by bytemunch** [comment]
Yeeeeah should be fun this one, I foresee no less than three hacky workarounds before it works 😅 

I'll aim for parity with HTML input placeholders

**Comment by Dimchikkk** [comment]
Niiice. Maybe placeholder is another editor? Basically CosmicBundle accepts new component placeholder that takes attrs and text value. Plugin spawns this entity with 2 buffers and makes placeholder visible only if text for main buffer is empty... something like this comes to mind.

**Comment by Dimchikkk** [comment]
Fixed by https://github.com/StaffEngineer/bevy_cosmic_edit/pull/74
