### ISSUE TITLE
Sometimes Backspace does not work

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#62]
On some runs, cannot delete characters in a buffer with backspace.
Some runs it works as expected.

WASM seems to work fine consistently (sample size of 10 refreshes, two builds)

**Comment by Dimchikkk** [comment]
It inconsistently broken on my machine: on some app runs I can remove by backspace, on others can't.

**Comment by bytemunch** [comment]
Oh yup just ran a couple more times, got a working backspace.

**Comment by bytemunch** [comment]
Being intermittent makes me think it's a scheduling issue, which would be inconsistent across builds for definite, I think the schedule can change the order of systems across runs too

**Comment by Dimchikkk** [comment]
Yep, most likely.
