### ISSUE TITLE
Obscured input, like `<input type='password'>` on web

### ISSUE THREAD

**Issue by bytemunch** [StaffEngineer/bevy_cosmic_edit#81]
Might be an optional component, replacing every character going in to the buffer with `•`.

Obscured input should not be copy or cuttable, but should accept paste.

Option to turn obscuring off via an event would be desirable, like the eye symbols on the web. This suggests a struct such as `pub struct PasswordInput { pub hidden: bool }`.

`editor.get_text()` should return the unobscured string, so the buffer must hold the actual text, only drawing an amount of • equal to the length of the buffer.

Hopefully displaying and holding different values doesn't mess up the click functions.

+ Default font should include the bullet point glyph to work out-of-the-box

**Comment by Dimchikkk** [comment]
Good idea 👍

**Comment by Dimchikkk** [comment]
Another idea: we could pull out https://github.com/StaffEngineer/velo/tree/main/crates/bevy_markdown from `velo` and have `markdown` mode for text widget :)
