### ISSUE TITLE
`CosmicEditPlugin` can break mouse capture

### ISSUE THREAD

**Issue by thatvertigo** [StaffEngineer/bevy_cosmic_edit#94]
When using `CosmicEditPlugin` alongside systems which attempt to lock the cursor, the cursor flickers when moved around, instead of staying hidden and locked.

**Comment by StaffEngineer** [comment]
There is an option to disable cursor handling fully and handle by yourself: https://github.com/StaffEngineer/bevy_cosmic_edit/blob/28e00c94476d79bf7a97382792cf07f579188592/src/lib.rs#L58

**Comment by thatvertigo** [comment]
Ah yes this was it, my. bad. Thanks for the help!
